services:
  qrkit:
    build: .
    # NÃO exponha portas manualmente no Compose para produção no Coolify!
    # Coolify vai cuidar do roteamento para você via domínio e HTTPS.
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - LIVEKIT_API_KEY=mykey
      - LIVEKIT_API_SECRET=mysecret
      - LIVEKIT_HOST=livekit:7880
      - DATABASE_URL=postgres://qrkit:qrkitpass@db:5432/qrkit?sslmode=disable
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
      - livekit

  livekit:
    image: livekit/livekit-server
    command: --config /livekit.yaml
    ports:
      - "7880:7880"
      - "7882:7882/udp" # Alinhado com udp_port: 7882 em livekit.yaml
      - "50000-50100:50000-50100/udp"
    volumes:
      - ./livekit.yaml:/livekit.yaml # Alterado de ./livekit-local.yaml
    environment:
      - "LIVEKIT_KEYS=mykey:mysecret"

  db:
    image: postgres:15
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: qrkit
      POSTGRES_PASSWORD: qrkitpass
      POSTGRES_DB: qrkit

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

volumes:
  db-data:
